name: Reusable workflow example B

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: false
        #required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Use a repo or org secret from the calling workflow.
      run: |
        echo secrets.token ${{ secrets.token }}
        echo inputs.config-path ${{ inputs.config-path }}
        echo secrets.CALLING_WORKFLOW_SECRET ${{ secrets.CALLING_WORKFLOW_SECRET }}
#    - uses: actions/labeler@v4
#      with:
#        repo-token: ${{ secrets.token }}
#        configuration-path: ${{ inputs.config-path }}


#on:
#  workflow_call:

#jobs:
#  pass-secret-to-action:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Use a repo or org secret from the calling workflow.
#        run: echo ${{ secrets.CALLING_WORKFLOW_SECRET }}

