name: Reusable workflow example A

on:
  workflow_dispatch:

jobs:
  pass-secrets-to-workflow:
    uses: ./.github/workflows/reusable-workflow-B.yml
    with:
      config-path: foo/.github/labeler.yml
    secrets: inherit

