---
name: "update-dist-check2-DOIT"

# https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      packedjspathjspath:
        required: true
        type: string
      packedjsstatuschanges:
        required: true
        type: string
      extractbranchbranch:
        required: true
        type: string
      testfoo:
        required: true
        type: string
    secrets:
      token:
        required: true

# on:
#  push:
#    branches:
#      - '*'
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
  
jobs:
  update-dist-check2-DOIT:
#    env:
#      #PACKED_JS_PATH: 'dist/index.js'
#      PACKED_JS_PATH: 'dist/restore/index.js dist/save/index.js'
#      #PACKED_JS_PATH: 'dist/restore/index.js'
    runs-on: ubuntu-latest
    if: inputs.packedjsstatuschanges
    steps:

      - name: Commit packed js
        id: commitPackedJs
        # if: steps.packedJsStatus.outputs.changes
          # git add ${{ env.PACKED_JS_PATH }}
          # git commit -m "Pack with dependencies to ${{ steps.packedJsStatus.outputs.changes }}"
        if: inputs.packedjsstatuschanges
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ inputs.packedjspathjspath }}
          git commit -m "Pack with dependencies to ${{ inputs.packedjsstatuschanges }}"
      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # tags: true
          # force: true
          # branch: ${{ steps.extractBranch.outputs.branch }}
          branch: ${{ inputs.extractbranchbranch }}
